name: mapbox/s3scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: action-node-setup
        uses: mapbox/gha@action-node-setup-v1
